### ISSUE TITLE
YouTube goes in bootloop when I try to use it to watch videos. 

### ISSUE THREAD

**Issue by Armandprogame** [GaryOderNichts/GiveMiiYouTube#12] opened 2024-05-13 13:43 UTC
Since I came out aroma 17, givemiiyoutube does not work by bootloop the youtube app (this problem is when you have 10 games or applications on wii u, or on usb or nand.

**Comment by Armandprogame** [comment] 2024-05-13 14:05
I confirm gary, since I came out aroma 17, youtube no longer works if you have too many apps on wii u

**Comment by GaryOderNichts** [comment] 2024-05-13 14:53
I am unable to reproduce this on Aroma Beta 20. Please update to Aroma Beta 20 and try again.

**Comment by Armandprogame** [comment] 2024-05-13 15:17
My Wii U already has aroma beta 20. And it works YouTube, but only if I don't have any application on the console. Just start downloading other apps, the YouTube app goes in bootloop Anyway I try to rinse aroma beta 20 but I don't think the error is aroma.

**Comment by Armandprogame** [comment] 2024-05-13 15:22
![17156137161586449736473458213115] (https://github.com/PretendoNetwork/GiveMiiYouTube/assets/115667084/e84a482e-fb20-4b06-988c-a11f19a6ecbe)
It remains like this.

**Comment by GaryOderNichts** [comment] 2024-05-13 15:42
I have several apps installed and cannot reproduce this issue. Please try to temporarily remove all plugins besides the AromaBasePlugin and GiveMiiYoutube.

**Comment by Armandprogame** [comment] 2024-05-13 15:44
ok now I'll try to remove all the plugins except aromabaseplugin,
givemiiyoutube and homebrew on wii u

Il Lun 13 Mag 2024, 17:42 GaryOderNichts ***@***.***> ha
scritto:

**Comment by Armandprogame** [comment] 2024-05-13 16:07
Ok Gary now works givemiiyoutube (possibly put a disclaimer where you say not to load too many plugins because givemiiyoutube might have problems)

**Comment by GaryOderNichts** [comment] 2024-05-13 18:08
One of your plugins is probably causing issues, this is unrelated to GiveMiiYoutube.
Try adding them back one by one and see which one causes the issues you described.

**Comment by Armandprogame** [comment] 2024-05-13 19:27
OK, now I've been cheating up all the plugins and now I see if the fault was something I knew. I knew it in practice time sync was in conflict with sntp client who in turn was in conflict with givemiiyoutube, sorry I fortunately deleted the plugin 
-------- Messaggio originale --------Da: GaryOderNichts ***@***.***> Data: 13/05/24  20:08  (GMT+01:00) A: PretendoNetwork/GiveMiiYouTube ***@***.***> Cc: Armandprogame ***@***.***>, Author ***@***.***> Oggetto: Re: [PretendoNetwork/GiveMiiYouTube] YouTube goes in bootloop when I try to use it to watch videos.  (Issue #12) 
One of your plugins is probably causing issues, this is unrelated to GiveMiiYoutube.
Try adding them back one by one and see which one causes the issues you described.

**Comment by GaryOderNichts** [comment] 2024-05-13 20:37
The SNTP Client is known to cause issues, please use [Wii-U-Time-Sync](https://github.com/Nightkingale/Wii-U-Time-Sync) instead. Anyways closing this as it's not a GiveMiiYouTube issue.

**Closed as not planned by GaryOderNichts** 2024-05-13 20:37 UTC
